config/routes.rb
Rorummi::Application.routes.draw do

  root :to => 'home#index'
  
  devise_for :users
  ActiveAdmin.routes(self)


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :forums

  resources :komentars


  resources :votes

  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :category, :description, :title

  validates :category, :title, :presence => true
<<<<<<< HEAD
has_many :komentar
=======

  has_many :votes
>>>>>>> 8fa1f0e5d8135a587d482a38dbf0deb6dc6e5efe
end

app/models/komentar.rb
class Komentar < ActiveRecord::Base
  attr_accessible :date_post, :description_komentar, :forum_id, :user_id
    belongs_to :forum
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :forums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forums }
    end
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
    @forum = Forum.find(params[:id])
    @komentars = @forum.komentar.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/new
  # GET /forums/new.json
  def new
    @forum = Forum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forum }
    end
  end

  # GET /forums/1/edit
  def edit
    @forum = Forum.find(params[:id])
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forums/1
  # PUT /forums/1.json
  def update
    @forum = Forum.find(params[:id])

    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy

    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!
  def index
  end
end

app/controllers/komentars_controller.rb
class KomentarsController < ApplicationController

    def show
        @komentar = Komentar.find(params[:id])    
    end

    def new
        @komentar = Komentar.new
    end

    def edit
        @komentar = Komentar.find(params[:id])
    end

    def create
        # forum = Forum.where(:id => params[:komentar][:forum_id]).first
        @komentar = Komentar.new(params[:komentar])
        if @komentar.save
            flash[:notice] = "Create new komentar Successfully"
            redirect_to forums_path
        else
            redirect_to forums_path
        end
    end

    def update
      @komentar = Komentar.find(params[:id])
      if @komentar.update_attributes (params[:komentar])
        flash[:notice] = "Update komentar Successfully"
        redirect_to :action => :index
      else
        render :action => :new
      end
    end

    def destroy
        @komentar = Komentar.find(params[:id])
        @komentar.destroy
        redirect_to komentars_path
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		forum = Forum.find(params[:forum_id])
		vote = forum.votes.build
		vote.save!
		redirect_to(forums_path)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/komentars_helper.rb
module KomentarsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Listing forums</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forums.each do |forum| %>
  <tr>
    <td><%= forum.title %></td>
    <td><%= forum.category %></td>
    <td><%= forum.description %></td>
    <td><%= pluralize(forum.votes.count, "vote") %></td>
    <td><%= button_to '+1', votes_path(forum_id: forum.id), method: :post %></td>
    <!-- <td><%= link_to 'Show', forum %></td>
    <td><%= link_to 'Edit', edit_forum_path(forum) %></td> -->
    <td><%= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum', new_forum_path %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @forum.title %>
</p>

<p>
  <b>Category:</b>
  <%= @forum.category %>
</p>

<p>
  <b>Description:</b>
  <%= @forum.description %>
</p>
		<div id='komentars'>	
			Komentar
			<br/>
				<% @komentars.each do |com| %>
				<%= com.description_komentar %><br/>
				<% end %>
	</div>
<div id='comment'>
	New Comment
<%= render :partial => "komentars/new" %>
</div>
<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/komentars/_new.html.erb
<%= form_for :komentar,:url => url_for(:controller => 'komentars', :action => 'create') do |form| %>
<br/>
	<%= form.text_area :description_komentar, :rows => '2' %><br/>
	<%= form.hidden_field :forum_id, :value => @forum.id %><br/>
	<%= submit_tag "Save" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorummi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>
<%= yield %>

</body>
</html>